<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="$(arg name)" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.33" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="depth" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->

  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="2" /> <!-- Link 2 -->
  <xacro:property name="height3" value="2" /> <!-- Link 3 -->
  <xacro:property name="height4" value="2" /> <!-- Link 4 -->

  <xacro:property name="motor_offset" value="-0.25" /> <!-- Link 4 -->  

  <xacro:property name="segmentmass" value="30" /> <!-- Link Mass -->

  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find tars_description)/urdf/tars.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find tars_description)/urdf/materials.xacro" />

  <xacro:macro name="leg" params="name offset height">
    <link name="${name}">
      <collision>
        <origin xyz="0 0 ${offset + motor_offset}" rpy="0 0 0"/>
        <geometry>
    <box size="${depth} ${width} ${height}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${offset + motor_offset}" rpy="0 0 0"/>
        <geometry>
    <box size="${depth} ${width} ${height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${offset}" rpy="0 0 0"/>
        <mass value="${segmentmass}"/>
        <inertia
      ixx="1.0" ixy="0.0" ixz="0.0"
      iyy="1.0" iyz="0.0"
      izz="1.0"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:leg name="link1" offset="0" height="${height1}" />
  <xacro:leg name="link2" offset="0" height="${height2}" />
  <xacro:leg name="link3" offset="0" height="${height3}" />
  <xacro:leg name="link4" offset="0" height="${height4}" />

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit velocity="1" effort="1000.0"/>
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit velocity="1" effort="1000.0"/>
  </joint>

  <joint name="joint3" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 ${width} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit velocity="1" effort="1000.0"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
